# Generated by Django 3.1.2 on 2021-06-22 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_auto_20210622_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='producto',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, to='apis.producto'),
        ),
    ]
